-- RedefineTables
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_USUARIO" (
    "CODUSU" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "EMAIL" TEXT NOT NULL,
    "SENHA" TEXT NOT NULL,
    "LOGADO" BOOLEAN,
    "INCLUSAO" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ALTERACAO" DATETIME NOT NULL
);
INSERT INTO "new_USUARIO" ("ALTERACAO", "CODUSU", "EMAIL", "INCLUSAO", "LOGADO", "SENHA") SELECT "ALTERACAO", "CODUSU", "EMAIL", "INCLUSAO", "LOGADO", "SENHA" FROM "USUARIO";
DROP TABLE "USUARIO";
ALTER TABLE "new_USUARIO" RENAME TO "USUARIO";
CREATE UNIQUE INDEX "USUARIO_EMAIL_key" ON "USUARIO"("EMAIL");
PRAGMA foreign_key_check;
PRAGMA foreign_keys=ON;
